### ISSUE TITLE
[bug] playing past a song's length

### ISSUE THREAD

**Issue by octarino** [vpaliyX/Flash#7]
As you see the song is 2m29s long and the position timestamp says I'm at 8m26s.

I'm playing from the recent list. Once the song has finished you tap on the last song and the play icon is in pause mode. At that time the timer starts going up. If the play screen is closed and opened again the timer is reset to the song's length and starts going up again. If I tap the pause button the timer is reset again to the song's length and starts going up again.

The expected behaviour would be to stop the timer when the last song finished and transform the pause into a play button that would play the current song from the beginning.

![4a2c683f-6893-47d0-a48a-89f6d9f12677](https://user-images.githubusercontent.com/22935424/31307554-8b140e6e-ab5e-11e7-8476-62711419dd2e.jpg)

**Comment by octarino** [comment]
Related to this. Play the last song. Hit pause. tap on the seekbar and the position is updated along with the timer. The song stays paused. Tap at the end and the buttons turns into the pause button and happens what's described above.

**Comment by vpaliyX** [comment]
I updated the app on Play Store, so you should get the update soon. Thanks for your effort.
